const transactionSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  type: { type: String, enum: ['purchase', 'rent', 'lease', 'payout'], required: true },
  amount: { type: Number, required: true },
  netAmount: { type: Number },
  platformFee: { type: Number, default: 0 },
  status: { type: String, enum: ['pending', 'processing', 'completed', 'failed'], default: 'pending' },
  method: { type: String, default: 'bank_transfer' },
  description: { type: String },
  bankName: { type: String },
  accountNumber: { type: String },
  accountName: { type: String },
  currency: { type: String, default: 'NGN' },
  createdAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now },
});